# Generated by Django 4.1.3 on 2024-12-24 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("emp_num", models.IntegerField()),
                ("name", models.CharField(max_length=250)),
                ("bank_name", models.CharField(max_length=250)),
                ("branch", models.CharField(blank=True, max_length=250, null=True)),
                ("account_number", models.CharField(max_length=250)),
                ("iban", models.CharField(max_length=250)),
                ("is_valid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=250)),
                ("password", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "emp_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ucasFinData.employee",
                    ),
                ),
            ],
        ),
    ]
