# Generated by Django 4.1.3 on 2024-12-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ucasFinData", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("emp_number", models.IntegerField()),
                ("name", models.CharField(max_length=250)),
                ("id_number", models.CharField(max_length=250)),
                ("birth_date", models.CharField(max_length=15)),
                ("phone", models.CharField(max_length=250)),
            ],
        ),
    ]
